# Generated by Django 4.1.4 on 2022-12-20 20:47
import django.contrib.gis.db.models.fields
from django.contrib.gis.geos import Point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0002_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                default=Point([0, 0]), srid=4326
            ),
            preserve_default=False,
        ),
    ]
