# Generated by Django 4.1.4 on 2022-12-26 22:09
import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0004_remove_place_latitude_remove_place_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326),
        ),
    ]
