# Generated by Django 4.1.4 on 2022-12-26 22:38
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0005_alter_place_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="place_id",
            field=models.CharField(default="", max_length=250),
            preserve_default=False,
        ),
    ]
