# Generated by Django 4.1.4 on 2022-12-29 23:51
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0006_place_place_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={"ordering": ["position"]},
        ),
        migrations.AlterField(
            model_name="image",
            name="position",
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
    ]
