# Generated by Django 4.1.4 on 2022-12-30 00:05
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0007_alter_image_options_alter_image_position"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="place",
            options={"ordering": ["id"]},
        ),
    ]
