# Generated by Django 4.1.4 on 2023-01-02 01:21
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0010_remove_place_place_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="description_short",
            field=models.TextField(),
        ),
    ]
