# Generated by Django 4.1.4 on 2023-01-02 01:25
import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0011_alter_place_description_short"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
