# Generated by Django 4.1.4 on 2023-01-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0012_alter_image_place"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="title",
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
